prgrms-be-devcourse/NBE2-3-1-team7

src/main/java/com/example/shop/domain/cart/CartDetail.java
src/main/java/com/example/shop/domain/cart/CartDetailRepository.java

feat:장바구니 목록 엔티티 추가

---

src/main/java/com/example/shop/auth/dto/SignUpRequest.java
src/main/java/com/example/shop/auth/service/AuthService.java
src/main/java/com/example/shop/domain/order/Order.java
src/main/java/com/example/shop/domain/order/OrderDetail.java
src/main/java/com/example/shop/domain/order/OrderStatus.java
src/main/java/com/example/shop/domain/product/Product.java
src/main/java/com/example/shop/domain/user/User.java
src/main/java/com/example/shop/domain/user/UserRepository.java
src/main/java/com/example/shop/global/config/auth/CustomUserDetailsService.java
src/main/java/com/example/shop/global/config/auth/JwtProvider.java

엔티티에 테이블명 지정 + OrderStatus 문구 수정
엔티티에 테이블명 지정 + OrderStatus 문구 수정

refactor:엔티티 테이블명 지정, 오타 수정

---

src/main/java/com/example/shop/auth/controller/AuthController.java
src/main/java/com/example/shop/auth/dto/EmailCodeRequest.java
src/main/java/com/example/shop/auth/repository/EmailCodeRepository.java
src/main/java/com/example/shop/auth/repository/RefreshTokenRepository.java
src/main/java/com/example/shop/auth/service/AuthService.java
src/main/java/com/example/shop/auth/service/EmailCodeUtil.java
src/main/java/com/example/shop/global/EmailSender.java
src/main/java/com/example/shop/global/config/AsyncConfig.java
src/main/java/com/example/shop/global/config/SecurityConfig.java
src/main/java/com/example/shop/global/config/auth/JwtAuthenticationFilter.java
src/main/java/com/example/shop/global/config/db/RedisConfig.java
src/main/java/com/example/shop/global/exception/EmailCreationException.java
src/main/java/com/example/shop/global/exception/EmailSendException.java
src/main/java/com/example/shop/global/exception/ErrorCodes.java
src/main/java/com/example/shop/global/response/GlobalExceptionHandler.java

> #12 
> 이메일 인증 코드를 발송하고 검증하는 API를 만들었습니다.
> 코드 위치 괜찮은지 봐주세요.

[feature] 이메일 인증 코드 메일 전송

---

src/main/java/com/example/shop/domain/cart/CartDetailRepository.java
src/main/java/com/example/shop/global/exception/ErrorCodes.java
src/main/java/com/example/shop/user/controller/CartController.java
src/main/java/com/example/shop/user/dto/AddCartProductRequest.java
src/main/java/com/example/shop/user/service/CartService.java

> #23, #14
> 1. 기존 장바구니에 같은 물품이 있으면 기존 물품에 수량이 증가하는 식으로 변경
2. 장바구니 추가 시 validation 추가
> 여기에 작성

Fix/#23 장바구니에 물품 추가 수정 + Refactor/#14 validation 추가

---

src/main/java/com/example/shop/domain/cart/CartDetailRepository.java
src/main/java/com/example/shop/global/exception/CartProductNotFoundException.java
src/main/java/com/example/shop/global/exception/ErrorCodes.java
src/main/java/com/example/shop/global/exception/NoAuthenticationException.java
src/main/java/com/example/shop/global/response/GlobalExceptionHandler.java
src/main/java/com/example/shop/global/util/SecurityUtil.java
src/main/java/com/example/shop/user/controller/CartController.java
src/main/java/com/example/shop/user/service/CartService.java

> #29 
> 1. 장바구니에 담긴 물품 삭제
2. 로그인한 유저의 이메일 가져오는 util 기능 생성
3. 에러 테스트 케이스를 입력해도 200 상태 코드가 나가는 오류 수정
4. 장바구니 서비스에서 로그인한 아이디 공통 로직 처리
> 여기에 작성

Feature/#29 장바구니에 담긴 물품 삭제

---

build.gradle
src/main/java/com/example/shop/user/controller/ProductController.java
src/main/java/com/example/shop/user/dao/UserDao.java
src/main/java/com/example/shop/user/dto/ProductResponse.java
src/main/java/com/example/shop/user/mapper/UserMapper.java
src/main/java/com/example/shop/user/service/ProductService.java
src/main/resources/application.yml
src/main/resources/mappers/usermapper.xml

> #22
> mybatis를 사용해(select문) 전체 메뉴 조회 및 상세 메뉴 조회 기능 구현
> 여기에 작성

feat: 메뉴 조회 기능 추가

---

build.gradle
src/main/java/com/example/shop/admin/controller/AdminProductController.java
src/main/java/com/example/shop/admin/dao/AdminDAO.java
src/main/java/com/example/shop/admin/dto/ProductTO.java
src/main/java/com/example/shop/admin/mapper/AdminMapper.java
src/main/java/com/example/shop/admin/service/AdminProductService.java
src/main/resources/application.yml
src/main/resources/mappers/adminMapper.xml

> feature/#18 물품생성
> yml에 카멜케이스 연동,ResponseEntity로 컨트롤러 적용 했습니다
> swagger에서 로그인하고 get으로 확인해주시면 됩니다!!

[feature] 물품 조회

---

src/main/java/com/example/shop/domain/cart/CartDetailRepository.java
src/main/java/com/example/shop/global/exception/CartEmptyException.java
src/main/java/com/example/shop/global/exception/ErrorCodes.java
src/main/java/com/example/shop/user/controller/CartController.java
src/main/java/com/example/shop/user/service/CartService.java

> #39 
> 1. 장바구니에 담긴 물품 전체 삭제
2. 장바구니에 담긴 특정 물품 삭제시 쿼리 최적화
3. 장바구니에 특정 기존 물품에 대한 존재여부 쿼리 최적화
> 여기에 작성

[feat] 장바구니에 담긴 물품 전체 삭제

---

src/main/java/com/example/shop/user/controller/CartController.java
src/main/java/com/example/shop/user/dto/UpdateCartQuantityRequest.java
src/main/java/com/example/shop/user/service/CartService.java

> #36 
> 장바구니에 담겨져 있는 특정 물품의 수량을 수정하는 기능입니다.
> 여기에 작성

[feat] 장바구니에 담긴 특정 물품 수량 변경 기능 추가

---

src/main/java/com/example/shop/admin/controller/AdminProductController.java
src/main/java/com/example/shop/admin/dao/AdminDAO.java
src/main/java/com/example/shop/admin/dto/ProductUpdateRequest.java
src/main/java/com/example/shop/admin/mapper/AdminMapper.java
src/main/java/com/example/shop/admin/service/AdminProductService.java
src/main/resources/application.yml
src/main/resources/mappers/adminMapper.xml

> Feature/#40 물품수정
> 상품 아이디를 입력하면 수정할 수 있게 했습니다
> swagger에 id를 입력하고 수정을 해주시길 바랍니다

[feature] 물품수정

---

src/main/java/com/example/shop/domain/cart/CartDetailRepository.java
src/main/java/com/example/shop/domain/order/DeliveryInfo.java
src/main/java/com/example/shop/domain/order/Order.java
src/main/java/com/example/shop/domain/order/OrderDetail.java
src/main/java/com/example/shop/domain/order/OrderRepository.java
src/main/java/com/example/shop/domain/product/Product.java
src/main/java/com/example/shop/domain/product/ProductRepository.java
src/main/java/com/example/shop/domain/user/User.java
src/main/java/com/example/shop/global/exception/CartEmptyException.java
src/main/java/com/example/shop/global/exception/EmptyCartException.java
src/main/java/com/example/shop/global/exception/EmptyOrderDetailException.java
src/main/java/com/example/shop/global/exception/ErrorCodes.java
src/main/java/com/example/shop/global/exception/NotEnoughQuantityException.java
src/main/java/com/example/shop/user/controller/CartController.java
src/main/java/com/example/shop/user/controller/OrderController.java
src/main/java/com/example/shop/user/dto/CreateOrderRequest.java
src/main/java/com/example/shop/user/dto/CreateOrderResponse.java
src/main/java/com/example/shop/user/service/CartService.java
src/main/java/com/example/shop/user/service/OrderService.java

> #42 
> 로그인한 회원의 장바구니에 담긴 물품들을 기준으로 주문을 생성합니다.(주문시 초기상태 PAID)
> 여기에 작성

[feat] 주문 생성

---

build.gradle
src/main/java/com/example/shop/admin/dao/OrderDeliveryRepository.java
src/main/java/com/example/shop/admin/dto/OrderDeliveryRequest.java
src/main/java/com/example/shop/admin/mapper/AdminMapper.java
src/main/java/com/example/shop/admin/service/OrderAdminService.java
src/main/java/com/example/shop/admin/service/OrderDeliveryUtil.java
src/main/java/com/example/shop/auth/service/AuthService.java
src/main/java/com/example/shop/batch/DeliveryOrderReader.java
src/main/java/com/example/shop/batch/OrderUpdateSenderWriter.java
src/main/java/com/example/shop/batch/config/EmailNotificationJobConfig.java
src/main/java/com/example/shop/batch/config/EmailScheduler.java
src/main/java/com/example/shop/batch/util/OrderDeliveryBatchUtil.java
src/main/java/com/example/shop/domain/cart/CartDetailRepository.java
src/main/java/com/example/shop/domain/order/OrderRepository.java
src/main/java/com/example/shop/domain/product/ProductRepository.java
src/main/java/com/example/shop/domain/user/UserRepository.java
src/main/java/com/example/shop/global/config/AsyncConfig.java
src/main/java/com/example/shop/global/config/db/RedisConfig.java
src/main/java/com/example/shop/global/util/EmailSender.java
src/main/java/com/example/shop/user/service/OrderService.java
src/main/resources/application.yml
src/main/resources/mappers/adminMapper.xml
src/test/java/com/example/shop/admin/dao/OrderDeliveryRepositoryTest.java
src/test/java/com/example/shop/admin/service/OrderDeliveryUtilTest.java
src/test/java/com/example/shop/batch/OrderUpdateSenderWriterTest.java

> #24 
> spring batch를 이용해서 14시에 주문이 배송되면 이메일을 전송한다.
> Order가 생성될 때, 레디스에 캐싱하는 건 임의로 추가했는데 괜찮은지 확인 부탁드립니다.

[feature] 주문 배송 알림 메일 발송

---

src/main/java/com/example/shop/admin/dao/OrderDeliveryRepository.java
src/main/java/com/example/shop/admin/service/OrderAdminService.java
src/main/java/com/example/shop/batch/DeliveryOrderReader.java
src/main/java/com/example/shop/batch/OrderUpdateSenderWriter.java
src/main/java/com/example/shop/batch/util/OrderDeliveryBatchUtil.java
src/main/java/com/example/shop/user/service/OrderService.java
src/test/java/com/example/shop/admin/dao/OrderDeliveryRepositoryTest.java
src/test/java/com/example/shop/batch/OrderUpdateSenderWriterTest.java

> #60 
> 주문이 수정되면 캐싱 값도 수정되게 변경
> 캐싱된 주문 데이터를 수정하는 순서가 괜찮은지 확인 부탁드립니다.

[feat] 주문 정보 수정 시 캐싱된 주문 수정

---

src/main/java/com/example/shop/global/exception/ErrorCodes.java
src/main/java/com/example/shop/global/exception/ProductIdNotFoundException.java
src/main/java/com/example/shop/global/exception/ProductSearchEmptyException.java
src/main/java/com/example/shop/global/exception/ProductsEmptyException.java
src/main/java/com/example/shop/user/controller/ProductController.java
src/main/java/com/example/shop/user/service/ProductService.java

> #68 
> 예외 클래스를 추가해 예외 처리 로직 수정(ResponseEntity 메서드를 사용해 반환 -> 커스텀 예외 반환)
> 여기에 작성

[refactor] 예외 클래스 추가 및 예외 처리 로직 수정

---

src/main/java/com/example/shop/admin/controller/AdminOrderController.java
src/main/java/com/example/shop/admin/dto/OrderDeliveryListRequest.java
src/main/java/com/example/shop/admin/dto/OrderDeliveryRequest.java
src/main/java/com/example/shop/admin/service/AdminOrderService.java
src/main/java/com/example/shop/admin/service/OrderAdminService.java
src/main/java/com/example/shop/batch/OrderUpdateSenderWriter.java
src/main/java/com/example/shop/user/service/OrderService.java
src/test/java/com/example/shop/batch/OrderUpdateSenderWriterTest.java

> #65 
> 관리자 주문 배송 일괄 처리 API를 만들었다.
>

[feat] 관리자 주문 배송 일괄 처리

---

src/main/java/com/example/shop/domain/order/OrderRepository.java
src/main/java/com/example/shop/user/controller/OrderController.java
src/main/java/com/example/shop/user/service/OrderService.java

> #74 
> 배송 시작전 상태인 특정 주문에 대해서 주문자는 주문을 취소할 수 있습니다.
> 여기에 작성

feat: 주문 취소 기능 추가

---

build.gradle
src/main/java/com/example/shop/admin/service/OrderDeliveryUtil.java
src/main/java/com/example/shop/auth/service/EmailCodeUtil.java
src/main/java/com/example/shop/global/util/TemplateEnginUtil.java
src/main/resources/templates/auth-code-email.html
src/main/resources/templates/delivery-email.html
src/test/java/com/example/shop/admin/service/OrderDeliveryUtilTest.java
src/test/java/com/example/shop/auth/service/EmailCodeUtilTest.java

> #73 
> 기존 HTML 소스코드가 자바 코드에 하드코딩 되어 있었는데, 따로 html 파일을 만들고 thymeleaf를 통해 파싱한다.
> 여기에 작성

[refactor] html 하드 코딩 리팩터링

---

src/main/java/com/example/shop/global/exception/ErrorCodes.java
src/main/java/com/example/shop/global/exception/ProductsSearchByOneLetterException.java
src/main/java/com/example/shop/user/controller/ProductController.java
src/main/java/com/example/shop/user/dao/UserDao.java
src/main/java/com/example/shop/user/dto/ProductDetailResponse.java
src/main/java/com/example/shop/user/dto/ProductResponse.java
src/main/java/com/example/shop/user/mapper/UserMapper.java
src/main/java/com/example/shop/user/service/ProductService.java
src/main/resources/mappers/usermapper.xml

> #82
> 전체 상품 조회 시 페이징 추가
잘못된 이름으로 상품 검색 시 모든 상품이 반환되는 버그 수정
잘못된 형식/값의 responseBody 반환 버그 수정
> 여기에 작성

[refactor] 전체 상품 조회 페이징 및 버그 수정

---

src/main/java/com/example/shop/admin/controller/AdminOrderController.java
src/main/java/com/example/shop/admin/dto/OrderSearchRequest.java
src/main/java/com/example/shop/domain/order/OrderRepository.java
src/main/java/com/example/shop/domain/order/OrderRepositoryImpl.java
src/main/java/com/example/shop/user/controller/CartController.java
src/main/java/com/example/shop/user/controller/OrderController.java
src/main/java/com/example/shop/user/dto/CartResponse.java

> #79 
> 리팩토링 작업과 Swagger 관련 어노테이션 추가했습니다
> 여기에 작성

[docs] 장바구니 주문 swagger 어노테이션 추가

---

src/main/java/com/example/shop/auth/controller/AuthController.java
src/main/java/com/example/shop/auth/dto/ReIssueTokenRequest.java
src/main/java/com/example/shop/auth/service/AuthService.java

close #90 
액세스 토큰 재발급 request 변경했습니다

fix: 토큰 재발급 request 수정

---

README.md

> 
> 프로젝트 발표 ppt 내용을 png로 변환한 다음 markdown으로 변경하였습니다. 
>

[docs] 프로젝트 소개
